# Site settings
title: Web developer diary
name: lokeshjain2008
description: > # comment
 tutorials for the ruby, ruby on rails, ror and some web technologies that include javascript.
 web technologies that includes html, html5, jQuery, PHP, Agular, Angularjs, react, reactjs, web-apps Python, Bootstrap css framework GAE etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lokeshjain2008.github.io/" # the base hostname & protocol for your site
twitter_username: lokeshjain2008
github_username:  lokeshjain2008

# Build settings
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

future: true

disqus_shortname: lokeshjain2008


# This is the way to include plugins in the project #by mistake i wrote `plugins:[]`
# gems: [ "font-awesome.rb"]

exclude: [Gemfile, Gemfile.lock, Rakefile]

# you can change the post url behaviour using permalink
# permalink: /:title

gems:
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME