# Site settings
title: Web developer diary
description: > # comment
 tutorials for the ruby, ruby on rails, ror and some web technologies that include javascript.
 web technologies that includes html, html5, jQuery, PHP, Python, Bootstrap css framework GAE etc.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://lokeshjain2008.github.io/" # the base hostname & protocol for your site
twitter_username: lokeshjain2008
github_username:  lokeshjain2008

# Build settings
markdown: redcarpet
permalink: pretty
disqus_shortname: lokeshjain2008


# This is the way to include plugins in the project #by mistake i wrote `plugins:[]`
# gems: [ "font-awesome.rb"]

exclude: [Gemfile, Gemfile.lock, Rakefile]

# you can change the post url behaviour using permalink
# permalink: /:title

gems:
  - jekyll-sitemap
